  name: Java CI

  on:
    - push
    - pull_request

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - name: Set up JDK 20
        - uses: actions/setup-java@v3
          with:
            java-version: '20'
            distribution: 'temurin'

        - name: build with Gradle
        - uses: gradle/gradle-build-action@v2
          with:
            gradle-version: 8.2.1
        - run: ./gradlew build

        - name: Make code coverage
          uses: paambaati/codeclimate-action@v3.2.0
          env:
            CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
            JACOCO_SOURCE_PATH: app/src/main/java
          with:
            debug: true
            coverageCommand: make -C app report
            coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml
#      - run: ./gradlew checkstyleMain
#      - run: ./gradlew test

