DEFAULT_GOAL := build-run

run-test:
	./build/install/app/bin/app /home/newcomer/java-project-71/app/src/main/resources/file1.json src/main/resources/file2.json
run-help:
	./build/install/app/bin/app -h
run-vers:
	./build/install/app/bin/app -V
run-dist:
	./build/install/app/bin/app /home/newcomer/java-project-71/app/src/main/resources/f1.json src/main/resources/f2.json

.PHONY: build
