name: Java CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.2.1'
          arguments: build
          build-root-directory: app
      - run: ./gradlew checkstyleMain
      - run: ./gradlew test
#      name: Set jacoco.xml path for code climate
#      - run: ACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter/cc-test-reporter format-coverage ./build/reports/jacoco/test/jacocoTestReport.xml --input-type jacoco
#      name: Upload code climate report
#      - run: ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID
